### ISSUE TITLE
As a stakeholder, I want to view and use an Invision-based prototype so that I can see how the pages interact with each other.

### ISSUE THREAD

**Issue by YaseenMM** [nyu-software-engineering/spring-2020-crystal-balboa#2]
### Acceptance criteria: 
- [x] Create a link to the readable Invision prototype
- [x] Allow each button or perceived action on the prototype to link to another page, presumably one that makes sense in proper context

**Comment by EdwardCheung99** [comment]
Prototype has been completed. https://projects.invisionapp.com/share/MGW6PTTJ4HP#/screens/407491823_Login_Page
