### ISSUE TITLE
As a developer, I want to become familiar with React.js, so that the front end can be created.

### ISSUE THREAD

**Issue by EdwardCheung99** [nyu-software-engineering/spring-2020-crystal-balboa#4]

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2020 - spikes should be treated on the task board the same as tasks.  In other words, this should not be in the Sprint Backlog column, but rather in one of the other columns that reflect its level of completion.

Also, this represents work that each developer must do individually - for example, if one developer learns React and moves this task to the Completed column, that does not mean that all other developers have also completed it.  So this should really be broken up into multiple tasks - one spike assigned to each developer independently.
